[project]
name = "distributed-worker-pool"
version = "0.1.0"
description = "Distributed system composed of a master scheduler and multiple workers. The master enqueues the top sites per country (Semrush), and workers download pages in parallel using a Redis shared message queue."
authors = [
    {name = "Iancu Stefan-Teodor", email = "iancustefanteodor@gmail.com"}
]
license = "LICENSE"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "redis (>=7.1.0,<8.0.0)"
]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
